include_recipe "../cookbooks/system/default.rb"
include_recipe "../cookbooks/users/default.rb"
include_recipe "../cookbooks/nginx/install.rb"
include_recipe "../cookbooks/redis/default.rb"
include_recipe "../cookbooks/mongodb/default.rb"
include_recipe "../cookbooks/mysql/community.rb"
include_recipe "../cookbooks/plenv/default.rb"
include_recipe "../cookbooks/rbenv/default.rb"
include_recipe "../cookbooks/ndenv/default.rb"

