include_recipe '../cookbooks/system/default.rb'
include_recipe '../cookbooks/users/default.rb'
include_recipe '../cookbooks/plenv/default.rb'
include_recipe '../cookbooks/rbenv/default.rb'
include_recipe '../cookbooks/ndenv/default.rb'
include_recipe '../cookbooks/goenv/default.rb'
include_recipe '../cookbooks/nginx/default.rb'
include_recipe '../cookbooks/redis/default.rb'
include_recipe '../cookbooks/mongodb/default.rb'
include_recipe '../cookbooks/mysql/default.rb'

